### ISSUE TITLE
Does Hugo support step numbers for cross referencing?

### ISSUE THREAD

**Issue by amcginlay** [amcginlay/k8s-primer#18]

**Comment by bwer432** [comment]
Ashish Lohoti describes autonumbering within pages = https://codingnconcepts.com/hugo/auto-number-headings-hugo/
Hugo page variables support access to the `.Weight` = https://gohugo.io/variables/page/
But I haven't yet put one and one together to get two. (i.e. need to track down where we want the styles)
Looking to do something like {{.Weight}}.{{h2}}.{{h3}}. (not the right syntax)?
Are step numbers like 019.4. or 019.4.2. okay? Or do we want to set a variable that renders the whole kit & caboodle and gives us single-level numbers for all pages in a section?

**Comment by amcginlay** [comment]
Steps as per Qwiklabs. If we can do that, awesome!

**Comment by amcginlay** [comment]
A nice to have. We'll get by without if necessary.

**Comment by amcginlay** [comment]
So frustrating.
We have these things called page variables, but nothing to do fetch-and-increment style iterator.
I just want to say something like (pseudocode):

Step {{ .nextStep }}

Job done. But, nada!

**Comment by amcginlay** [comment]
This, maybe ... ¯\_(ツ)_/¯

**Comment by bwer432** [comment]
{{< step >}}
Add this code around your steps.
{{< /step >}}

Adjust the style at the end of ./static/css/theme-mine.css as needed, and we could make the shortcode defined at ./layouts/shortcodes/step.html to perhaps add a parameter for color, size, or prefix, such as "Step 1. " instead of the current "1. " 

Closing, can re-open as needed.
